### ISSUE TITLE
how to do for inference

### ISSUE THREAD

**Issue by hahashayebuhui** [akhilpm/DroneDetectron2#1]
Hello, I simply want to use pictures to inference to get the result, what can I  do?

**Comment by akhilpm** [comment]
You could call a plotter function from "inference_with_crops" function defined in inference.py. At inference, you are getting instance predictions on each image. The plotter utility function then reads the image using its data_dict and plot the instance predictions. There is a plotter utility function built-in with detectron2, you can use that. I used the following code to create visualizations for the paper.

```python
def plot_detection_boxes(predictions, data_dict):
    img = Image.open(data_dict["file_name"])
    plt.axis('off')
    plt.imshow(img)
    ax = plt.gca()    
    if len(predictions)!=0:
        predictions = predictions[predictions.scores>0.6]
        predictions = predictions.pred_boxes.tensor.cpu()
        for bbox in predictions:
            x1, y1 = bbox[0], bbox[1]
            h, w = bbox[3]-bbox[1], bbox[2]-bbox[0]
            rect = Rectangle((x1, y1), w, h, linewidth=2, edgecolor='orange', facecolor='none')
            ax.add_patch(rect)
    im_name = os.path.basename(data_dict["file_name"])[:-4]
    plt.savefig(os.path.join('./temp', im_name+"_det_Dcrop.jpg"), dpi=90, bbox_inches='tight')
    #plt.savefig(os.path.join('./temp', im_name+"_det_Base.jpg"), dpi=90, bbox_inches='tight')
    #plt.show()
    plt.clf()
``` 

This is for visualizing predictions during evaluation. If you don't want to do an evaluation, but simply get predictions passing a single or group of images, please refer to the detectron2 visualization documentation. You can use the following snippet to create visualizations with detectron2
```python
from detectron2.utils.visualizer import Visualizer
from PIL import Image
import numpy as np
import os

def plot_detections(predictions, data_dict, metadata, cfg):
    img = np.array(Image.open(data_dict["file_name"]))
    visualizer = Visualizer(img, metadata=metadata)
    visualizer.draw_instance_predictions(predictions)
    save_path = os.path.join(cfg.OUTPUT_DIR, "detections", data_dict["file_name"].split('/')[-1])
    vis.save(save_path)
```
