### ISSUE TITLE
checkpoint 

### ISSUE THREAD

**Issue by AI-AUT** [akhilpm/DroneDetectron2#10]
please share your training checkpoints.
thanks

**Comment by akhilpm** [comment]
It is a big file, I cannot host it in my GitHub.

**Comment by xavibou** [comment]
Hi, I am interested in the checkpoints as well. Could you store them on a google drive directory and share the link?
Thanks!

**Comment by akhilpm** [comment]
Hello, I don't have them with me now. Our compute clusters periodically delete the checkpoint files from the "scratch" storage system.
