### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by mahilaMoghadami** [akhilpm/DroneDetectron2#18]
hello
how can I inference trained model with sample image and visualize output?
is it implemented in your github?

thank you

**Comment by akhilpm** [comment]
You can use detectron2 visulization tools itself, it already provides such basic utilities. 

I have also created some utilities here for plotting to get the figures in the paper:
https://github.com/akhilpm/DroneDetectron2/blob/main/utils/plot_utils.py

Here for instance you can see how it is used:
https://github.com/akhilpm/DroneDetectron2/blob/main/croptrain/engine/inference.py#L69

**Comment by AQUAY16** [comment]
Sorry, when I use the code evaluation model, I still don't know how to set the code to visualize the final image and box results, and how to save the results in the detections directory  。
python train_net.py \
      --eval-only \
      --num-gpus 1 \
      --config-file configs/Base-RCNN-FPN.yaml \
      MODEL.WEIGHTS <your weight>.pth

**Comment by AQUAY16** [comment]
Add CROPTEST PREDICT.ONLY True can predict an image

**Comment by wliu23** [comment]
> Sorry, when I use the code evaluation model, I still don't know how to set the code to visualize the final image and box results, and how to save the results in the detections directory 。 python train_net.py --eval-only --num-gpus 1 --config-file configs/Base-RCNN-FPN.yaml MODEL.WEIGHTS .pth

Hello, I have the same problem. Have you solved it yet？
