### ISSUE TITLE
FPS measuring

### ISSUE THREAD

**Issue by AI-AUT** [akhilpm/DroneDetectron2#19]
as I analyse your paper, you must have better FPS than other complex models such as GLSAN and etc.
but you didnt report any thing.
how can I measure your trained model inference time and FPS?

appreciate if help.
thanks.

**Comment by akhilpm** [comment]
FPS is reported in tables 1,2 and 5 in the paper. 

You can also see s/img printed in terminal (or saved to log file) when inference is performed. Inverting that will give FPS!
