### ISSUE TITLE
result question

### ISSUE THREAD

**Issue by zuikeaideren** [akhilpm/DroneDetectron2#20]
![1693812011313](https://github.com/akhilpm/DroneDetectron2/assets/79903646/213412a3-0871-4587-947b-1908a2562756)
![1693812117784](https://github.com/akhilpm/DroneDetectron2/assets/79903646/a7c0172a-d658-4576-91e4-78a963057617)
Hello, I used the statement python train_net.py --num-gpus 1 --config-file configs/RCNN-FPN-CROP.yaml OUTPUT_DIR outputs_FPN_CROP_VisDrone to reproduce the code, and the final result is quite different from the original paper. There is a big gap, and the AP obtained by the motor is 0. What is the reason for this?

**Comment by starkLJ** [comment]
Hello, I have the same problem, did you find the reason?

**Comment by akhilpm** [comment]
Refer to issue #16 and #2. Before creating new issues, please refer to old one's to see if they are already addressed.

**Comment by zuikeaideren** [comment]
I did not change the code, the original json file was run by myself, and then I changed the json file to the one given by the author, now the motor is no longer 0.
