### ISSUE TITLE
Problems during reimplementation

### ISSUE THREAD

**Issue by starkLJ** [akhilpm/DroneDetectron2#21]
First of all, thank you very much for your excellent work. I've been trying to replicate your results, but I've encountered some issues, and I hope you can help me with them. Firstly, the results I obtained during replication did not match the results mentioned in the paper (AP 33.02, AP50 57.87, AP75 33.09), and there is a significant difference. Below are the training and testing commands I used:

Training:
```
python train_net.py --num-gpus 1 --config-file configs/RCNN-FPN-CROP.yaml OUTPUT_DIR outputs_FPN_CROP_VisDrone
```

Testing:
```
python train_net.py --eval-only --num-gpus 1 --config-file configs/RCNN-FPN-CROP.yaml MODEL.WEIGHTS <your weight>.pth
```

I hope you can point out any mistakes I may have made. Thanks again.

**Comment by akhilpm** [comment]
Check the issue #16.

**Comment by zuikeaideren** [comment]
Can you share your R-50.pkl with me, thank you

**Comment by akhilpm** [comment]
It is not mine in any regard. I downloaded it from the source mentioned in Detectron2's official code.

**Comment by zuikeaideren** [comment]
![image](https://github.com/akhilpm/DroneDetectron2/assets/79903646/3b88c307-633a-463e-89e2-4a00d0c75ee9)
I downloaded R-50.pkl here, is it the correct pkl file?

**Comment by akhilpm** [comment]
Yes

**Comment by zuikeaideren** [comment]
Okay, then the difference in experimental results should be a configuration problem, thank you.
