### ISSUE TITLE
train with other detectrors

### ISSUE THREAD

**Issue by AI-AUT** [akhilpm/DroneDetectron2#23]
hello
as you mentioned in your paper, it is possible to use any detector to train with your model.
how can I do it? 
I mean how to train yolo with your method? 

thank you

**Comment by akhilpm** [comment]
You can refer to how I did for FCOS, and Faster RCNN in this code base and extend it to whichever you want.

relevant main files: train_fcos.py, train_net.py

**Comment by AI-AUT** [comment]
thanks
could you please refer me a link to help me?
I dont know how to start.
steps I should go, any usefull link, or any thing usefull?
