### ISSUE TITLE
dataset path for train

### ISSUE THREAD

**Issue by mahilaMoghadami** [akhilpm/DroneDetectron2#3]
hello
thank you for your implementation sharing
I want to train my model which is a part of visdrone dataset. where I should set my dataset path?
I prepare dataset as structure you said in my drive but I don't know where should I set path.
also there is no field in config file to set address.

thank you.

**Comment by akhilpm** [comment]
Hi, 

In the implementation provided, I set a variable called "data_dir" in the main function. Here is the line doing that:

https://github.com/akhilpm/DroneDetectron2/blob/main/train_net.py#L48

You can also modify the config file to add this path directly there if you prefer that way(for example add a field cfg.DATA_DIR). The data can be anywhere in your drive and you create symbolic links to that. In my case, I was using a Slurm scheduler and pointing data_dir to the "temp" directory of the server.
