### ISSUE TITLE
crop labeling and augmentation part 

### ISSUE THREAD

**Issue by mahilaMoghadami** [akhilpm/DroneDetectron2#30]
Hello Akhil
based on your paper: ' Then we augment the training set with the higher resolution version of the density crops, and the corresponding ground truth (GT) boxes of objects inside the crop' 
I can't find this part of your pipeline in your released code.
could you please help me to understand?

I want to modify it and read and searched a lot in your code, but I didn't find it.
Also, I didn't find the crop labeling code, if it exists in this repository, please help me to find it.

thank you.

**Comment by akhilpm** [comment]
It is done in the load function of each dataset. Simple to find, and related utility functions are there in the utils as well. See for example

https://github.com/akhilpm/DroneDetectron2/blob/main/croptrain/data/datasets/visdrone.py#L262

Crop labeling also happens in the function you call from that line.
