### ISSUE TITLE
checkpoint not found

### ISSUE THREAD

**Issue by yinntag** [akhilpm/DroneDetectron2#31]
Thank you for the great work! Can you provide the checkpoint file?

AssertionError: Checkpoint /home/akhil135/PhD/DroneDetectron2/pretrained_models/R-50.pkl not found!

**Comment by yinntag** [comment]
ss

**Comment by Yhsun20001116** [comment]
Hello, has it been resolved? I also encountered this problem

**Comment by yinntag** [comment]
I download it at https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md.

**Comment by Yhsun20001116** [comment]
非常感谢您的帮助，这个问题已经解决了，但是我又遇到了这个问题，不知道您有没有遇到过。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akhilpm/DroneDetectron2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月22日(星期一) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akhilpm/DroneDetectron2] checkpoint not found (Issue #31)





 
I download it at https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md.
