### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by liuw20** [akhilpm/DroneDetectron2#33]
please provide the pretrained model(R-50.pkl) in order to repeat your result. Thanks

**Comment by akhilpm** [comment]
Hi, the pre-trained checkpoints are obtained from here:
[https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md](https://github.com/facebookresearch/detectron2/blob/main/MODEL_ZOO.md)

Thank you.
