### ISSUE TITLE
DDP  inference with crops

### ISSUE THREAD

**Issue by liuw20** [akhilpm/DroneDetectron2#34]
Hello, when I train model used 'python train_net.py  --num-gpus 4 --config-file configs/RCNN-FPN-CROP.yaml  OUTPUT_DIR outputs_FPN_VisDrone' , error occur！

Is it not possible to use multiple GPUs for parallel training?

**Comment by akhilpm** [comment]
The trainer functionalities are inherited from the base Detectron2 package, so it should support DDP. If I remember correctly, I trained most of the models on DOTA with multiple GPUs. 

Check what is the exact error in your case. I don't expect any big issues in the multi-GPU training or inference.

**Comment by liuw20** [comment]
![image](https://github.com/akhilpm/DroneDetectron2/assets/72062754/db423a62-55ab-49fb-83c6-08e54c23adf5)

when I trained the model with multiple GPUs , an error will appear  as shown in the  figure above.  Only with GPUs=1，it is normal

**Comment by akhilpm** [comment]
Can you try to use model.module when you use multiple GPUs. 
[https://github.com/pytorch/pytorch/blob/1f71ac785c3c690069300fa04e59da68ae598114/torch/nn/parallel/distributed.py#L1402-L1403](https://github.com/pytorch/pytorch/blob/1f71ac785c3c690069300fa04e59da68ae598114/torch/nn/parallel/distributed.py#L1402-L1403)

For example, change the line 67 to
```
if comm.get_world_size() > 1:
      all_outputs = model.module(inputs, infer_on_crops=True, cfg=cfg)
else:
      all_outputs = model(inputs, infer_on_crops=True, cfg=cfg)
```
Don't forget to import comm `import detectron2.utils.comm as comm`

Normally this should happen internally, but I am not getting why it is not happening. The error log you posted is only partial.

**Comment by liuw20** [comment]
thanks
your attitude is admirable
