### ISSUE TITLE
DOTA issue

### ISSUE THREAD

**Issue by zuikeaideren** [akhilpm/DroneDetectron2#39]
Hello, after training the DOTA data set, why do the final results I get differ so much from the results in the paper? Can you help me analyze it and answer it? If you need me to provide additional documents, please let me know, thank you.
![image](https://github.com/akhilpm/DroneDetectron2/assets/79903646/c0f71879-354b-4178-931c-883ad272b52b)

**Comment by akhilpm** [comment]
It is because the current config file is using 10% data points (I changed the settings to 10% for some experiments and forgot to change it back, sorry). I updated the config file.

**Comment by zuikeaideren** [comment]
thank you for your answer
