### ISSUE TITLE
yolo or FasterRCNN config file

### ISSUE THREAD

**Issue by mahilaMoghadami** [akhilpm/DroneDetectron2#4]
hello
I want to train a model with YOLO or FasterRCNN config files which there arent in configs folder.
could you please help me?
or a guide to help me prepare this config?
thank you.

**Comment by akhilpm** [comment]
I provided the implementation of Faster RCNN and FCOS detector in this code base.  It is mentioned in the paper as well, please go through it for more implementation details. Faster RCNN is called "GeneralizedRCN" in detectron2. See the "Base-RCNN-FPN.yaml" config file. The "CropRCNN" model in "RCNN-FPN-CROP.yaml" for density crop-based training is derived from the original Faster RCNN.

If you want YOLO, you might have to do the adaptation work; the part for doing projection, crop extraction, data loader preparation, etc can be used from here.
