### ISSUE TITLE
Unable to resolve this error

### ISSUE THREAD

**Issue by AQUAY16** [akhilpm/DroneDetectron2#40]
Can you help me see why there are errors in this place

![962573538d3e815eaa8cf36601d2159](https://github.com/akhilpm/DroneDetectron2/assets/129248493/3d851dfb-97b9-423d-84ea-58b7f9203387)

**Comment by AQUAY16** [comment]
![e1f6893fd65f4c70e0dac20987b67d8](https://github.com/akhilpm/DroneDetectron2/assets/129248493/318df8af-24b1-4078-b660-1ba39f90f9e5)

**Comment by AQUAY16** [comment]
There should be an error with label data of 0

**Comment by AQUAY16** [comment]
When I changed the label_dicts in line 79 to unlabel_dicts, it seemed like there was no problem
![6ba732c211510ae8a13c8396f7b9145](https://github.com/akhilpm/DroneDetectron2/assets/129248493/2c3aa2ca-7877-429b-bbf1-4d6c272fc4a6)

**Comment by AQUAY16** [comment]
I found that this error occurs on my Windows system and requires this modification, while it runs normally on Linux system

**Comment by akhilpm** [comment]
You might have made some changes in the config file. You can even remove the call to divide_label_unlabel function, I just used it to make a random split of the data for some debugging. SUP_PERCENT variable in the config file controls how many samples are in labeled and unlabeled dicts. Set it to 100 always.

**Comment by sjdch** [comment]
https://github.com/yuxuan-life请问你解决了么？是不是根据作者的思想修改的？
