### ISSUE TITLE
is the crops really help improving performance?

### ISSUE THREAD

**Issue by twangnh** [akhilpm/DroneDetectron2#45]
@akhilpm Hi, thanks for shairng the code, we tried simply set the  confidence threshold of selecting the crop to 1.0, thus no crop is maintained and only original image is used, but the performance is very close to that of using crops as the default model of the paper. has anyone came across this situation?

**Comment by akhilpm** [comment]
@twangnh Thank you for your interest in our work.

This is discussed in #44. Please refer to it. 

Akhil
